title: Bricklead AL Guidelines
description: Bricklead AL Guidelines

markdown: kramdown

kramdown:
  toc_levels: 2..6     # TOC à partir des h2 (jusqu'à h6)
  input: GFM           # compatibilité GitHub Flavored Markdown
